

User.destroy_all


genre1 = Genre.create(name: 'rock')
genre2 = Genre.create(name: 'pop')
genre3 = Genre.create(name: 'jazz')
genre4 = Genre.create(name: 'indie')
genre5 = Genre.create(name: 'jingle')
genre6 = Genre.create(name: 'blues')
genre7 = Genre.create(name: 'folk')
genre8 = Genre.create(name: 'funk')
genre9 = Genre.create(name: 'gospel')
genre10 = Genre.create(name: 'techno')
genre11 = Genre.create(name: 'metal')
genre12 = Genre.create(name: 'pop')
genre13 = Genre.create(name: 'k-pop')
genre14 = Genre.create(name: 'j-pop')
genre15 = Genre.create(name: 'classical')



guitar = Instrument.create(name: 'guitar')
drums = Instrument.create(name: 'drums')
bass_guitar = Instrument.create(name: 'bass_guitar')
mandolin = Instrument.create(name: 'mandolin')
accordion = Instrument.create(name: 'accordion')
bagpipes = Instrument.create(name: 'bagpipes')
banjo = Instrument.create(name: 'banjo')
clarinet = Instrument.create(name: 'clarinet')
fiddle = Instrument.create(name: 'fiddle')
flute = Instrument.create(name: 'flute')
harmonica = Instrument.create(name: 'harmonica')
piano = Instrument.create(name: 'piano')
ukulele = Instrument.create(name: 'ukulele')
alto_saxophone = Instrument.create(name: 'alto_saxophone')
tenor_saxophone = Instrument.create(name: 'tenor_saxophone')
trumpet = Instrument.create(name: 'trumpet')

new_york = City.create(name: 'New York')
los_angeles = City.create(name: "Los Angeles")
nashville = City.create(name: "Nashville")


beans = User.create(name: 'beans', email: 'beans@beans.com', password: 'password', city: new_york)
eman = User.create(name: 'eman', email: 'eman@eman.com', password: 'password', city: los_angeles)
raoul = User.create(name: 'raoul', email: 'raoul@raoul.com', password: 'password', city: nashville)
daniel = User.create(name: 'daniel', email: 'daniel@daniel.com', password: 'password', city: new_york)
sylvester = User.create(name: 'sylvester', email: 'sylvester@sylvester.com', password: 'password', city: los_angeles)
licorice = User.create(name: 'licorice', email: 'licorice@licorice.com', password: 'password', city: nashville)
charlie = User.create(name: 'charlie', email: 'charlie@charlie.com', password: 'password', city: new_york)
tigernan = User.create(name: 'tigernan', email: 'tigernan@tigernan.com', password: 'password', city: los_angeles)
raja = User.create(name: 'raja', email: 'raja@raja.com', password: 'password', city: nashville)
miles = User.create(name: 'miles', email: 'miles@miles.com', password: 'password', city: new_york)
willy = User.create(name: 'willy', email: 'willy@willy.com', password: 'password', city: los_angeles)
pat = User.create(name: 'pat', email: 'pat@pat.com', password: 'password', city: los_angeles)
natsu = User.create(name: 'natsu', email: 'natsu@natsu.com', password: 'password', city: nashville)
alex = User.create(name: 'alex', email: 'alex@alex.com', password: 'password', city: new_york)
roy = User.create(name: 'roy', email: 'roy@roy.com', password: 'password', city: new_york)
rollie = User.create(name: 'rollie', email: 'rollie@rollie.com', password: 'password', city: new_york)
ido = User.create(name: 'ido', email: 'ido@ido.com', password: 'password', city: new_york)
maxim = User.create(name: 'maxim', email: 'maxim@maxim.com', password: 'password', city: new_york)
quin = User.create(name: 'quin', email: 'quin@quin.com', password: 'password', city: new_york)
liko = User.create(name: 'liko', email: 'liko@liko.com', password: 'password', city: los_angeles)
bugra = User.create(name: 'bugra', email: 'bugra@bugra.com', password: 'password', city: los_angeles)
jeff = User.create(name: 'jeff', email: 'jeff@jeff.com', password: 'password', city: new_york)
leigh = User.create(name: 'leigh', email: 'leigh@leigh.com', password: 'password', city: new_york)
sam = User.create(name: 'sam', email: 'sam@sam.com', password: 'password', city: new_york)




UserGenre.create(user: beans, genre: genre1)
UserGenre.create(user: eman, genre: genre2)
UserGenre.create(user: raoul, genre: genre3)
UserGenre.create(user: daniel, genre: genre4)
UserGenre.create(user: sylvester, genre: genre5)
UserGenre.create(user: licorice, genre: genre6)
UserGenre.create(user: charlie, genre: genre7)
UserGenre.create(user: tigernan, genre: genre8)
UserGenre.create(user: raja, genre: genre9)
UserGenre.create(user: miles, genre: genre10)
UserGenre.create(user: willy, genre: genre11)
UserGenre.create(user: pat, genre: genre12)
UserGenre.create(user: natsu, genre: genre13)
UserGenre.create(user: alex, genre: genre14)
UserGenre.create(user: roy, genre: genre15)
UserGenre.create(user: rollie, genre: genre1)
UserGenre.create(user: ido, genre: genre2)
UserGenre.create(user: maxim, genre: genre3)
UserGenre.create(user: quin, genre: genre4)
UserGenre.create(user: liko, genre: genre5)
UserGenre.create(user: bugra, genre: genre6)
UserGenre.create(user: jeff, genre: genre7)
UserGenre.create(user: leigh, genre: genre8)
UserGenre.create(user: sam, genre: genre9)


UserInstrument.create(user: beans, instrument: guitar)
UserInstrument.create(user: eman, instrument: drums)
UserInstrument.create(user: raoul, instrument: ukulele)
UserInstrument.create(user: daniel, instrument: drums)
UserInstrument.create(user: sylvester, instrument: bass_guitar)
UserInstrument.create(user: licorice, instrument: mandolin)
UserInstrument.create(user: charlie, instrument: accordion)
UserInstrument.create(user: tigernan, instrument: bagpipes)
UserInstrument.create(user: raja, instrument: banjo)
UserInstrument.create(user: willy, instrument: clarinet)
UserInstrument.create(user: pat, instrument: fiddle)
UserInstrument.create(user: natsu, instrument: flute)
UserInstrument.create(user: alex, instrument: harmonica)
UserInstrument.create(user: roy, instrument: piano)
UserInstrument.create(user: rollie, instrument: alto_saxophone)
UserInstrument.create(user: ido, instrument: tenor_saxophone)
UserInstrument.create(user: maxim, instrument: trumpet)
UserInstrument.create(user: quin, instrument: guitar)
UserInstrument.create(user: liko, instrument: drums)
UserInstrument.create(user: bugra, instrument: bass_guitar)
UserInstrument.create(user: jeff, instrument: mandolin)
UserInstrument.create(user: leigh, instrument: drums)
UserInstrument.create(user: sam, instrument: bagpipes)



friendship1 = Friendship.create(user: beans, friend: eman)
friendship2 = Friendship.create(user: raoul, friend: beans)
friendship3 = Friendship.create(user: beans, friend: daniel)
friendship4 = Friendship.create(user: beans, friend: raja)
friendship5 = Friendship.create(user: beans, friend: eman)
friendship6 = Friendship.create(user: beans, friend: willy)
friendship7 = Friendship.create(user: beans, friend: sylvester)
friendship8 = Friendship.create(user: beans, friend: jeff)
friendship9 = Friendship.create(user: beans, friend: licorice)
friendship10 = Friendship.create(user: beans, friend: charlie)


request_1 = FriendRequest.create(sender: beans, recipient: eman)
request_2 = FriendRequest.create(sender: beans, recipient: raoul)
request_3 = FriendRequest.create(sender: beans, recipient: daniel)
